version: "3.7"

services:
  db_challenge_chapterv:
    image: postgres
    container_name: db_challenge_chapterv
    restart: always
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=docker
      - POSTGRES_DB=fin_api
    volumes:
      - pgdata:/data/postgres
    
volumes:
  pgdata:
    driver: local